home-assistant-mqtt: change patches op from add to replace
Error: add operation does not apply:
doc is missing path:
"/metadata/annotations/"metallb.io/loadBalancerIPs"": missing value