Revert "jellyfin: use builtin httpRoute support for external"
Error: template: jellyfin/templates/NOTES.txt:127:52:
executing "jellyfin/templates/NOTES.txt" at <0>:
matches is not a method but has arguments

This reverts commit 25bcaa2ebd93c7592553fcea42d108e3cab9ba84.